### ISSUE TITLE
Missing dotenv dependancy.

### ISSUE THREAD

**Issue by occs** [thebearingedge/pg-bump#43]
# What I expected.
To run `pg-bump` without errors.

# What I experienced instead.
I received an error when running `pg-bump`.

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'dotenv/config'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pg-bump/build/cli.js:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by thebearingedge** [comment]
Thanks! It's a [`peerDependency`](https://github.com/thebearingedge/pg-bump/blob/72a001c0ca78ec458819f1839a285e8c31305727/package.json#L45).
